# Generated by Django 4.1 on 2023-11-05 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='symbol',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterModelTable(
            name='stock',
            table='master-stock',
        ),
    ]
